# I hyprpaper started with uwsm then, to resrart it use:
# systemctl --user restart hyprpaper.service

# Write this in ./local/wallpaper.conf
# wallpaper {
#     monitor =
#     path = <path_to_wallpaper>
# }
source = ~/.config/hypr/local/wallpaper.conf
splash = false
